import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TodoContextProvider } from '@/components/providers/currency-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Indospace1',
    description: 'Generated by indospace'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TodoContextProvider>{children}</TodoContextProvider>
            </body>
        </html>
    );
}
